---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    kubernetes.io/metadata.name: airflow
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: env=airflow
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  namespace: airflow
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1
