FROM 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3

RUN pip install catboost joblib pandas scikit-learn numpy xgboost boto3==1.16.4 botocore==1.19.4 cryptography==3.4.6 ruamel_yaml>=0.11.14 
