apiVersion: v1
kind: Namespace
metadata:
  name: kserve-models
  labels:
    kubernetes.io/metadata.name: kserve-models
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: env=kserve-models
spec:
  finalizers:
  - kubernetes
