version: 0.2


env:
  parameter-store:
    ssh_key: klarna-case-deploy-key
    ssh_pub: klarna-case-deploy-key.pub
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y python3
      - python3 -m pip install black
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Get ssh key
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/klarna-deploy-key
      - echo "$ssh_pub" > ~/.ssh/klarna-deploy-key.pub
      - chmod 600 ~/.ssh/klarna-deploy-key
      - eval "$(ssh-agent -s)"
      - echo Check airflow-app code
      - python3 -m black --check airflow-app/
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - scp -i ~/.ssh/klarna-deploy-key airflow-app/configs/* admin@ec2-54-88-231-167.compute-1.amazonaws.com:~/airflow-configs/
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
